source 'https://github.com/CocoaPods/Specs.git’
platform :ios, ’12.0'

target 'FabulousApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FabulousApp
    #Swift必装
    pod 'SnapKit'
    pod 'IQKeyboardManagerSwift'
    pod 'Kingfisher', '~> 6.0'
    pod 'Alamofire', '~> 5.2'
    pod 'ESPullToRefresh'
    #Objective-C必装
    pod 'MBProgressHUD'
    pod 'FDFullscreenPopGesture'
    pod 'YYText'

  target 'FabulousAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FabulousAppUITests' do
    # Pods for testing
  end

end
